# Generated by Django 2.1.7 on 2020-03-29 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0002_meeting_last_result_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meeting',
            old_name='prev_meeting_last_shuffle_time',
            new_name='prev_meeting_last_result_time',
        ),
    ]
