# Generated by Django 2.2.9 on 2020-04-04 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0003_auto_20200329_2300'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': '등록된 회사(Company)', 'verbose_name_plural': '등록된 회사(Company)'},
        ),
        migrations.AlterModelOptions(
            name='joineduser',
            options={'verbose_name': '미팅지원자 현황(JoinedUser)', 'verbose_name_plural': '미팅지원자 현황(JoinedUser)'},
        ),
        migrations.AlterModelOptions(
            name='kakaochatting',
            options={'verbose_name': '카카오 채팅방 URL(KakaoChatting)', 'verbose_name_plural': '카카오 채팅방 URL(KakaoChatting)'},
        ),
        migrations.AlterModelOptions(
            name='matching',
            options={'verbose_name': '미팅 모집 내 개별 각각의 매칭(Matching)', 'verbose_name_plural': '미팅 모집 내 각각의 개별 매칭(Matching)'},
        ),
        migrations.AlterModelOptions(
            name='meeting',
            options={'verbose_name': '미팅 모집(Meeting)', 'verbose_name_plural': '미팅 모집(Meeting)'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': '회원/팀정보(Profile)', 'verbose_name_plural': '회원/팀정보(Profile)'},
        ),
        migrations.AlterModelOptions(
            name='validation',
            options={'verbose_name': '이메일 인증코드(Validation)', 'verbose_name_plural': '이메일 인증코드(Validation)'},
        ),
        migrations.RenameField(
            model_name='joineduser',
            old_name='already_met_one',
            new_name='already_met_first',
        ),
        migrations.RenameField(
            model_name='joineduser',
            old_name='already_met_three',
            new_name='already_met_second',
        ),
        migrations.RenameField(
            model_name='joineduser',
            old_name='already_met_two',
            new_name='already_met_third',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='image',
            new_name='image_first',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='image_three',
            new_name='image_second',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='image_two',
            new_name='image_third',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='validated',
            new_name='is_validated',
        ),
        migrations.AlterField(
            model_name='meeting',
            name='close_time',
            field=models.DateTimeField(help_text='미팅 선착순이 닫히는 시간'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='cutline',
            field=models.IntegerField(blank=True, help_text='남 vs 여 중 적은 숫자의 매칭지원자수', null=True),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='description',
            field=models.CharField(blank=True, help_text='미팅 공지문', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='first_shuffle_time',
            field=models.DateTimeField(help_text='1번째 섞는 시간 / 즉, first met에서 second met으로 넘어가는 시간'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='last_result_time',
            field=models.DateTimeField(help_text='모든 미팅매칭 프로세스가 종료되는 시간', null=True),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='location',
            field=models.CharField(help_text='실제 미팅 만나는 오프라인 약속 기준 장소', max_length=20),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='meeting_time',
            field=models.DateTimeField(help_text='실제 미팅 만나는 오프라인 약속 기준 시간'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='open_time',
            field=models.DateTimeField(help_text='미팅 선착순이 열리는 시간'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='prev_meeting_last_result_time',
            field=models.DateTimeField(help_text='지난번 미팅매칭 프로세스가 종료되었던 시간', null=True),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='second_shuffle_time',
            field=models.DateTimeField(help_text='2번째 섞는 시간 / 즉, second met에서 third met으로 넘어가는 시간'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='third_shuffle_time',
            field=models.DateTimeField(help_text='3번째 섞는 시간 / 즉, third met에서 last met으로 넘어가는 시간'),
        ),
    ]
