# Generated by Django 2.1.7 on 2019-08-02 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kakaochatting',
            old_name='kakao_chattingroom',
            new_name='chattingroom_url',
        ),
    ]
