# Generated by Django 2.1.7 on 2019-08-13 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matching',
            name='trial_time',
            field=models.IntegerField(default=-1),
        ),
    ]
