# Generated by Django 2.1.7 on 2019-06-23 00:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meetingmatching',
            name='text',
        ),
        migrations.AddField(
            model_name='meetingmatching',
            name='cutline',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='meetingmatching',
            name='location',
            field=models.CharField(default=3, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meetingmatching',
            name='meeting_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meetingmatching',
            name='mid_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meetingmatching',
            name='starting_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
