# Generated by Django 2.1.7 on 2019-06-23 00:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0002_auto_20190623_0927'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingmatching',
            name='final_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
