# Generated by Django 2.1.7 on 2019-08-02 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0002_auto_20190802_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joineduser',
            name='matching',
            field=models.ManyToManyField(blank=True, through='meeting.Matching', to='meeting.JoinedUser'),
        ),
    ]
