# Generated by Django 2.1.7 on 2019-06-23 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0003_meetingmatching_final_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingmatching',
            name='current_process',
            field=models.IntegerField(default=0),
        ),
    ]
