# Generated by Django 2.1.7 on 2019-07-14 09:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('meeting', '0004_meetingmatching_current_process'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20)),
                ('domain', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='JoinedUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_matched', models.BooleanField(default=False)),
                ('rank', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Matching',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trial_time', models.IntegerField(default=1)),
                ('is_greenlight_male', models.BooleanField(default=False)),
                ('is_greenlight_female', models.BooleanField(default=False)),
                ('is_gift_male', models.BooleanField(default=False)),
                ('is_gift_female', models.BooleanField(default=False)),
                ('kakao_chattingroom', models.URLField(null=True)),
                ('joined_female', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='joined_female', to='meeting.JoinedUser')),
                ('joined_male', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='joined_male', to='meeting.JoinedUser')),
            ],
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open_time', models.DateTimeField()),
                ('first_shuffle_time', models.DateTimeField()),
                ('second_shuffle_time', models.DateTimeField()),
                ('third_shuffle_time', models.DateTimeField()),
                ('location', models.CharField(blank=True, max_length=20)),
                ('cutline', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='')),
                ('is_male', models.BooleanField(null=True)),
                ('age_range', models.IntegerField(null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_login_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('team_introduce', models.TextField(blank=True, null=True)),
                ('last_intro_modified_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_img_modified_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='meeting.Company')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='MeetingMatching',
        ),
        migrations.AddField(
            model_name='joineduser',
            name='matching',
            field=models.ManyToManyField(through='meeting.Matching', to='meeting.JoinedUser'),
        ),
        migrations.AddField(
            model_name='joineduser',
            name='meeting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meeting.Meeting'),
        ),
        migrations.AddField(
            model_name='joineduser',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meeting.Profile'),
        ),
    ]
