# Generated by Django 2.1.7 on 2019-07-20 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0006_auto_20190714_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matching',
            name='kakao_chattingroom',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='meeting_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_img_modified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_intro_modified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
