# Generated by Django 2.1.7 on 2019-07-23 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0007_auto_20190720_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joineduser',
            name='rank',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='team_introduce',
            field=models.TextField(blank=True, default=''),
        ),
    ]
