export const DELETE_POPUP = "DELETE_POPUP";
export const DELETE_POPUP_JOIN = "DELETE_POPUP_JOIN";
export const CREATE_COPIED_POPUP = "CREATE_COPIED_POPUP";
export const CREATE_JOINED_POPUP = "CREATE_JOINED_POPUP";
export const GET_MEETING_INFO = "GET_MEETING_INFO";